//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compgame.BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int TovarID { get; set; }
        public string TovarArticleNumber { get; set; }
        public string TovarName { get; set; }
        public int ManufacturerName { get; set; }
        public int TovarQuantityInStock { get; set; }
        public Nullable<byte> TovarDiscountAmount { get; set; }
        public string SalesMan { get; set; }
        public decimal TovarCost { get; set; }
        public string TovarPhoto { get; set; }
        public string TovarDescription { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
